### PR TITLE
Enhanced the lookup script to trim or remove the description field

### PR DESCRIPTION
**Pull request by GrantStreetGroup**
Enhanced the lookup script to trim or remove the description field, so that the message sent out is not too large.

### CODE REVIEW

**Comment by savagegus** [comment]
Could you resolve the conflicts?

**Comment by danoc** [comment]
:+1: I was going to implement the same thing. I'd love to see this get merged in.

**Comment by savagegus** [comment]
I'd be happy to merge this, but it still shows conflicts, if you can resolve that would be great.

**Comment by danoc** [comment]
@GrantStreetGroup – Maybe kill the `console.log`s, too?

**Comment by savagegus** [comment]
:+1:

**Comment by GrantStreetGroup** [comment]
@savagegus ready to merge?

**Comment by savagegus** [comment]
done, sorry i missed that.

**Pull request merged**
